version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: ".github/workflows" # Location of package manifests
  schedule:
    interval: "monthly"
  groups:
    actions:
      patterns:
        - "*"
