# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

compiler: gcc

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

env:
    global:
        - PYTHON_VERSION=3.6
        - EVENT_TYPE='push pull_request'

matrix:
    include:
        # Run pytest suite
        - name: test linux
          os: linux

        # Run pytest suite
        - name: test osx
          os: osx
          osx_image: xcode10.2

before_install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

install:
    # Install MIRaGe dependencies
    - conda env update -f=environment.yml
    # Install development versions of webbpsf and poppy
    - conda uninstall poppy
    - git clone git@github.com:spacetelescope/webbpsf.git
    - pip install -e webbpsf/
    - git clone git@github.com:spacetelescope/poppy.git
    - pip install -e poppy/
    # Install MIRaGe package
    - pip install -e .

script:
    - pytest ./tests/
