name: mirage_osx
channels:
  - http://ssb.stsci.edu/astroconda
  - http://ssb.stsci.edu/astroconda-dev
  - conda-forge
  - defaults
dependencies:
  - alabaster>=0.7.12
  - appnope>=0.1.0
  - asdf>=2.1.0.dev1+ga161518
  - asn1crypto>=0.24.0
  - astropy>=3.1.2
  - astroquery>=0.3.8
  - atomicwrites>=1.2.1
  - attrs>=18.2.0
  - babel>=2.6.0
  - backcall>=0.1.0
  - beautifulsoup4>=4.6.3
  - blas>=1.0
  - bleach>=2.1.4
  - bokeh>=0.13.0
  - ca-certificates>=2018.8.24
  - certifi>=2018.8.24
  - cffi>=1.11.5
  - cfitsio>=3.440
  - chardet>=3.0.4
  - click>=6.7
  - cloudpickle>=0.5.6
  - crds>=7.2.6.dev143+g1c80b2c
  - cryptography>=2.3.1
  - cycler>=0.10.0
  - cython>=0.28.5
  - cytoolz>=0.9.0.1
  - dask>=0.19.2
  - dask-core>=0.19.2
  - decorator>=4.3.0
  - distributed>=1.23.2
  - docutils>=0.14
  - drizzle>=1.10.dev2+gbec16a2
  - entrypoints>=0.2.3
  - filelock>=3.0.8
  - fitsverify>=4.18
  - freetds>=1.00.9
  - freetype>=2.9.1
  - gwcs>=0.10a.dev25+g75a2435
  - h5py>=2.8.0
  - hdf5>=1.10.2
  - healpy>=1.11.0
  - heapdict>=1.0.0
  - html5lib>=1.0.1
  - icu>=58.2
  - idna>=2.7
  - imageio>=2.4.1
  - imagesize>=1.1.0
  - intel-openmp>=2019.0
  - ipykernel>=5.0.0
  - ipython>=6.5.0
  - ipython_genutils>=0.2.0
  - ipywidgets>=7.4.2
  - jedi>=0.12.1
  - jinja2>=2.10
  - jpeg>=9b
  - jplephem>=2.8.dev1+gc1b4c18
  - jsonschema>=2.6.0
  - jupyter>=1.0.0
  - jupyter_client>=5.2.3
  - jupyter_console>=5.2.0
  - jupyter_core>=4.4.0
  - keyring>=13.2.1
  - kiwisolver>=1.0.1
  - libcxx>=4.0.1
  - libcxxabi>=4.0.1
  - libedit>=3.1.20170329
  - libffi>=3.2.1
  - libgcc>=4.8.5
  - libgfortran>=3.0.1
  - libiconv>=1.15
  - libpng>=1.6.34
  - libsodium>=1.0.16
  - libtiff>=4.0.9
  - libxml2>=2.9.8
  - libxslt>=1.1.32
  - locket>=0.2.0
  - lockfile>=0.12.2
  - lxml>=4.2.5
  - markupsafe>=1.0
  - matplotlib>=3.0.0
  - mistune>=0.8.3
  - mkl>=2018.0.3
  - mkl_fft>=1.0.4
  - mkl_random>=1.0.1
  - more-itertools>=4.3.0
  - mpmath>=1.0.0
  - msgpack-python>=0.5.6
  - namedlist>=1.7
  - nbconvert>=5.3.1
  - nbformat>=4.4.0
  - nbsphinx>=0.3.5
  - ncurses>=6.1
  - networkx>=2.1
  - notebook>=5.7.0
  - numpy>=1.14.3
  - numpy-base>=1.14.3
  - olefile>=0.46
  - openssl>=1.0.2p
  - packaging>=17.1
  - pandas>=0.23.4
  - pandoc>=2.3.1
  - pandocfilters>=1.4.2
  - parsley>=1.3
  - parso>=0.3.1
  - partd>=0.3.8
  - pexpect>=4.6.0
  - photutils>=0.6
  - pickleshare>=0.7.4
  - pillow>=5.3.0
  - pip>=10.0.1
  - pluggy>=0.7.1
  - prometheus_client>=0.3.1
  - prompt_toolkit>=1.0.15
  - psutil>=5.4.7
  - ptyprocess>=0.6.0
  - py>=1.6.0
  - pycparser>=2.19
  - pygments>=2.2.0
  - pymssql>=2.1.3
  - pyopenssl>=18.0.0
  - pyparsing>=2.2.1
  - pyqt>=5.6.0
  - pysocks>=1.6.8
  - pysynphot>=0.9.12
  - pytest>=3.8.1
  - pytest-arraydiff>=0.2
  - pytest-astropy>=0.4.0
  - pytest-doctestplus>=0.1.3
  - pytest-openfiles>=0.3.0
  - pytest-remotedata>=0.3.0
  - pytest-runner>=4.2
  - python==3.6
  - python-dateutil>=2.7.3
  - pytz>=2018.5
  - pywavelets>=1.0.0
  - pyyaml>=3.13
  - pyzmq>=17.1.2
  - qt>=5.6.2
  - qtconsole>=4.4.1
  - readline>=7.0
  - requests>=2.19.1
  - scikit-image>=0.14.0
  - scikit-learn>=0.20.0
  - scipy>=1.1.0
  - semantic_version>=2.6.0
  - send2trash>=1.5.0
  - setuptools>=40.2.0
  - simplegeneric>=0.8.1
  - sip>=4.18.1
  - six>=1.11.0
  - snowballstemmer>=1.2.1
  - sortedcontainers>=2.0.5
  - spherical-geometry>=1.2.1.dev11+g5b65401
  - sphinx>=1.8.1
  - sphinx_rtd_theme>=0.4.1
  - sphinxcontrib-websupport>=1.1.0
  - sqlite>=3.25.2
  - stsci.image>=2.3.0.dev0+g720cb3a
  - stsci.imagestats>=1.5.3.dev0+g9f0dbc0
  - stsci.stimage>=0.2.2.dev0+g7049ddc
  - stsci.tools>=3.4.13.dev0+g5f25467
  - tblib>=1.3.2
  - terminado>=0.8.1
  - testpath>=0.3.1
  - tk>=8.6.8
  - toolz>=0.9.0
  - tornado>=5.1.1
  - traitlets>=4.3.2
  - unixodbc>=2.3.4
  - urllib3>=1.23
  - verhawk>=0.0.3.dev0+g4f4a60c
  - wcwidth>=0.1.7
  - webbpsf-data>=0.7.0
  - webencodings>=0.5.1
  - wheel>=0.31.1
  - widgetsnbextension>=3.4.2
  - xz>=5.2.4
  - yaml>=0.1.7
  - zeromq>=4.2.5
  - zict>=0.1.3
  - zlib>=1.2.11
  - pip:
    - et-xmlfile>=1.0.1
    - jdcal>=1.4
    - jwst>=0.13.3
    - jwst-backgrounds>=1.1.1
    - jwxml>=0.3.0
    - numpydoc>=0.9.1
    - openpyxl>=2.5.8
    - poppy>=0.7.0
    - pysiaf>=0.2.5
    - relic>=1.1.2
    - stsci-image>=2.3.0
    - stsci-imagestats>=1.5.3
    - stsci-stimage>=0.2.2
    - stsci-tools>=3.4.13
    - webbpsf>=0.8.0
