channels:
- http://ssb.stsci.edu/astroconda
- conda-forge
- defaults
dependencies:
- pip
- python==3.8.5
- pip:
    - asdf>=2.7.2
    - astropy>=4.2
    - astroquery>=0.4.1
    - batman-package
    - crds>=10.3.5
    - gwcs>=0.16.1
    - healpy>=1.14
    - h5py>=3.1.0
    - ipython>=7.19.0
    - jupyter>=1.0.0
    - jwst
    - jwst-backgrounds>=1.1.1
    - jwxml>=0.3.2
    - lxml>=4.6.2
    - matplotlib>=3.3.4
    - numpy>=1.19.5
    - photutils>=1.0.2
    - pysiaf>=0.10.0
    - pytest>=6.2.2
    - scipy>=1.6.0
    - sphinx>=3.4.3
    - synphot>=1.0.1
    - pyyaml>=5.4.1
    - webbpsf>=0.9.1
    - git+https://github.com/npirzkal/GRISMCONF
    - git+https://github.com/npirzkal/NIRCAM_Gsim
