name: mirage_linux
channels:
- http://ssb.stsci.edu/astroconda-dev
- conda-forge
- http://ssb.stsci.edu/astroconda
- defaults
dependencies:
- alabaster>=0.7.11
- asn1crypto>=0.24.0
- astroquery>=0.3.8
- babel>=2.6.0
- beautifulsoup4>=4.6.3
- blas>=1.0
- bleach>=2.1.4
- bokeh>=0.13.0
- ca-certificates>=2018.8.24
- certifi>=2018.8.24
- cycler>=0.10.0
- defusedxml>=0.5.0
- distributed>=1.23.2
- docutils>=0.14
- entrypoints>=0.2.3
- gmp>=6.1.2
- healpy>=1.12.4
- html5lib>=1.0.1
- idna>=2.7
- imageio>=2.4.1
- imagesize>=1.1.0
- ipykernel>=5.0.0
- ipython>=6.5.0
- ipywidgets>=7.4.2
- jedi>=0.12.1
- jeepney>=0.4
- jinja2>=2.10
- jupyter>=1.0.0
- jupyter_client
- jupyter_console>=5.2.0
- jupyter_core>=4.4.0
- keyring>=13.2.1
- libgcc>=7.2.0
- libgfortran>=3.0.0
- libsodium>=1.0.16
- locket>=0.2.0
- lockfile>=0.12.2
- mistune>=0.8.3
- more-itertools>=4.3.0
- nbconvert>=5.5.0
- nbformat>=4.4.0
- nbsphinx>=0.3.5
- networkx>=2.1
- notebook>=5.7.0
- openssl>=1.0.2p
- pandoc>=2.3
- pandocfilters>=1.4.2
- partd>=0.3.8
- pexpect>=4.6.0
- pickleshare>=0.7.4
- pip>=10.0.1
- prometheus_client>=0.3.1
- ptyprocess>=0.6.0
- pyopenssl>=18.0.0
- pytest>=3.8.1
- pytest-runner>=4.2
- pyzmq>=17.1.2
- qtconsole>=4.4.1
- requests>=2.19.1
- secretstorage>=3.1.0
- send2trash>=1.5.0
- setuptools>=40.2.0
- six>=1.11.0
- snowballstemmer>=1.2.1
- sphinx>=1.8.1
- sphinx_rtd_theme>=0.4.1
- sphinxcontrib-websupport>=1.1.0
- terminado>=0.8.1
- testpath>=0.3.1
- traitlets>=4.3.2
- urllib3>=1.23
- wcwidth>=0.1.7
- webencodings>=0.5.1
- wheel>=0.31.1
- widgetsnbextension>=3.4.2
- zeromq>=4.2.5
- atomicwrites>=1.2.1
- attrs>=18.2.0
- backcall>=0.1.0
- cffi>=1.11.5
- chardet>=3.0.4
- click>=6.7
- cloudpickle>=0.5.5
- cryptography>=2.3.1
- cython>=0.28.5
- cytoolz>=0.9.0.1
- dask>=0.19.2
- dask-core>=0.19.2
- dbus>=1.13.2
- decorator>=4.3.0
- expat>=2.2.6
- filelock>=3.0.8
- fontconfig>=2.13.0
- freetype>=2.9.1
- glib>=2.56.2
- gst-plugins-base>=1.14.0
- gstreamer>=1.14.0
- h5py>=2.8.0
- hdf5>=1.10.2
- heapdict>=1.0.0
- icu>=58.2
- intel-openmp>=2019.0
- ipython_genutils>=0.2.0
- jpeg>=9b
- jsonschema>=2.6.0
- kiwisolver>=1.0.1
- libedit>=3.1.20170329
- libffi>=3.2.1
- libgcc-ng>=8.2.0
- libgfortran-ng>=7.3.0
- libpng>=1.6.34
- libstdcxx-ng>=8.2.0
- libtiff>=4.0.9
- libuuid>=1.0.3
- libxcb>=1.13
- libxml2>=2.9.8
- libxslt>=1.1.32
- lxml>=4.2.5
- markupsafe>=1.0
- matplotlib>=3.0.0
- mkl>=2018.0.3
- mkl_fft>=1.0.4
- mkl_random>=1.0.1
- mpmath>=1.0.0
- msgpack-python>=0.5.6
- ncurses>=6.1
- numpy>=1.14.3
- numpy-base>=1.14.3
- olefile>=0.46
- packaging>=17.1
- pandas>=0.23.4
- parso>=0.3.1
- pcre>=8.42
- pillow>=5.2.0
- pluggy>=0.7.1
- prompt_toolkit>=1.0.15
- psutil>=5.4.7
- py>=1.6.0
- pycparser>=2.18
- pygments>=2.2.0
- pyparsing>=2.2.0
- pyqt>=5.9.2
- pysocks>=1.6.8
- pytest-arraydiff>=0.2
- pytest-astropy>=0.4.0
- pytest-doctestplus>=0.1.3
- pytest-openfiles>=0.3.0
- pytest-remotedata>=0.3.0
- python>=3.6.6
- python-dateutil>=2.7.3
- pytz>=2018.5
- pywavelets>=1.0.0
- pyyaml>=3.13
- qt>=5.9.6
- readline>=7.0
- scikit-image>=0.14.0
- scikit-learn>=0.20.0
- scipy>=1.1.0
- semantic_version>=2.6.0
- simplegeneric>=0.8.1
- sip>=4.19.8
- sortedcontainers>=2.0.5
- sqlite>=3.25.2
- tblib>=1.3.2
- tk>=8.6.8
- toolz>=0.9.0
- tornado>=5.1
- xz>=5.2.4
- yaml>=0.1.7
- zict>=0.1.3
- zlib>=1.2.11
- fitsverify>=4.18
- parsley>=1.3
- pysynphot>=0.9.12
- webbpsf-data>=0.7.0
- asdf>=2.1.0.dev1+ga161518
- astropy>=4.0.0.dev10786+gd099cfe
- cfitsio>=3.440
- crds>=7.2.6.dev105+ga1c1767
- drizzle>=1.10.dev2+gbec16a2
- freetds>=1.00.9
- gwcs>=0.10a.dev21+g75e92da
- jplephem>=2.8.dev0+g9926bb5
- jwst>=0.12.0a.dev115+g9d5eb8c
- namedlist>=1.7
- photutils>=0.6
- pymssql>=2.1.3
- spherical-geometry>=1.2.1.dev11+g5b65401
- stsci.image>=2.3.0.dev0+g720cb3a
- stsci.imagestats>=1.5.1.dev1+g8f96637
- stsci.stimage>=0.2.2.dev0+g7049ddc
- stsci.tools>=3.4.13.dev0+g5f25467
- unixodbc>=2.3.4
- verhawk>=0.0.3.dev0+g4f4a60c
- pip:
  - et-xmlfile>=1.0.1
  - ipython-genutils>=0.2.0
  - jdcal>=1.4
  - jupyter-client>=5.2.3
  - jupyter-console>=5.2.0
  - jupyter-core>=4.4.0
  - jwst-backgrounds>=1.1.1
  - jwxml>=0.3.0
  - mkl-fft>=1.0.4
  - mkl-random>=1.0.1
  - msgpack>=0.5.6
  - numpydoc>=0.9.1
  - openpyxl>=2.5.8
  - poppy>=0.7.0
  - prometheus-client>=0.3.1
  - prompt-toolkit>=1.0.15
  - pysiaf>=0.2.5
  - relic>=1.1.2
  - semantic-version>=2.6.0
  - sphinx-rtd-theme>=0.4.1
  - webbpsf>=0.8.0
